name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-22.04 # TODO: fix persistent tmp-path tests on ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Install ts-node
        run: npm install -g ts-node
      - name: Check if everything compiles
        run: tsc --noEmit
      - name: Build the code
        run: npm run build
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Build Electron code
        run: npm run build-electron
      - name: Run Playwright tests
        run: xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" -- npm run test
      - name: Run Playwright Electron tests
        run: xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" -- npm run test-electron
